### ISSUE TITLE
Archivated Einzelbäume should be displayed for 3 years

### ISSUE THREAD

**Issue by signedav** [opengisch/dbfwd#27]
Aktive Einzelbäume werden angezeigt und archivierte Einzelbäume (letzte 3 Jahre) anzeigen -> mit Flag "archviert". 

ABKLÄREN MIT DEUTSCHE BAHN:
Weshalb?
Ist archiviert hier in der Historischen Datenbank?

**Comment by m-kuhn** [comment]
> Ist archiviert hier in der Historischen Datenbank?

Meiner Meinung nach, Ja.

--------

@signedav man kann Formatierungen erzeugen mit

```
**Abklären mit Deutsche Bahn**
```

**Abklären mit Deutsche Bahn**

```
* Weshalb?
* Ist archiviert hier in der Historischen Datenbank?
```

 * Weshalb?
 * Ist archiviert hier in der Historischen Datenbank?
