### ISSUE TITLE
a_landkreis zu a_be_nr

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/dbfwd#54]
jb:

> *6.    Check: live.massnahmenbaum_gps_id()*
>     Das Folgende muss abgeändert werden:
>         a_landkreis soll ersetzt werden mit a_be_nr

**Comment by m-kuhn** [comment]
Im ganzen Skript oder nur spezifisch hier?

**Comment by signedav** [comment]
Das ist nur kosmetisch und nicht Funktional. Wird sowieso schon mit be_nr gemacht, allerdings heisst das Argument in der funktion dann a_landkreis - dies ist etwas verwirrend. Habs angepasst.

**Comment by signedav** [comment]
done
