### ISSUE TITLE
Neue Tabelle "Massnahmen Insitu"

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/dbfwd#7]
* be_flaeche
* Datum
* Bearbeiter
* Anzahl Massnahmen

**Comment by signedav** [comment]
@m-kuhn Brauche mehr Infos darüber.

**Comment by m-kuhn** [comment]
In QField (und also auch in den QField Views) soll bei den Bäumen jeweils ein Feld verfügbar sein, wo ein Bearbeiter für Einel- und Massnahmenbäume eintragen kann, wieviele Massnahmen vor Ort durchgeführt wurden (Numerisch, 0-10 oder so).
Dies ist "pro Besuch" zu verstehen. Ein Einzelbaum kann 2018 und 2020 jeweils kontrolliert und mit Sofortmassnahmen behandelt werden.
Massnahmenbäume wohl nur ein Mal (da sie das nächste Mal ja neu erfasst werden).

Anforderungen:

* Tabelle(n), wo die Info gespeichert werden soll (vermutlich auch ein Fremdschlüssel auf den betreffenden Baum, sehe ich im Originalissue gerade nirgends)
* Logik in den Views Einzel- und Massnahmenbaum für QField
  * Wird immer als 0 angezeigt
  * Falls beim Schreiben in die View ein Wert >0 eingegeben wird, werden die entsprechenden Einträge erzeugt / angepasst.

Wir müssen morgen abklären ob das so stimmt.

**Comment by signedav** [comment]
"Feld lassen wir da, aber haben keine weitere Verwendung mehr dafür."
